name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "src/frontend/**"
      - ".github/workflows/frontend-ci.yml"

  pull_request:
    branches:
      - main
    paths:
      - "src/frontend/**"
      - ".github/workflows/frontend-ci.yml"

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: production-grade-gitops/frontend

jobs:
  build-and-push:
    name: Build and Push Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::703707151858:role/production-grade-gitops-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./src/frontend
          file: ./src/frontend/Dockerfile
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest